server:
  port: 8001
spring:
  application:
    name: catalog-indexer
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  elasticsearch:
    host: localhost
    port: 9200
    scheme: http
    username: elastic
    password: ElasticRocks!
