server:
  port: 8000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  elasticsearch:
    host: localhost
    port: 9200
    scheme: http
    username: elastic
    password: ElasticRocks!

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitmq
    password: SolrRocks!

logging:
  level:
    org.elasticsearch: DEBUG
    com.sradutataru: ERROR
